### ISSUE TITLE
Cool plugin

### ISSUE THREAD

**Issue by MeetPing** [Mattx8y/iPunish#1]
Is there a config to make it look like hypixel because im making a server that im trying to make look and feel like hypixel.

 (Hi iWillBanU, havent seen you in a while. mind unblocking me in discord.)

**Comment by Mattx8y** [comment]
The plugin isn't done yet.

(And no, don't ask me again)

**Comment by MeetPing** [comment]
Tbh cool concept for a plugin tbh if I were you I would add ways to configure everything.
